### PR TITLE
set app version

### PR DESCRIPTION
**Pull request by hallyn**
So that 'mosctl --version' will show a meaningful value instead
of always 0.10.

Also change the gofmt in Makefile to only hit cmd/ and pkg/.
Otherwise it would frequently fail on irrelevant paths like
roots/

### CODE REVIEW

**Comment by hallyn** [comment]
```
serge@jerom ~/src/project-machine/mos$ ./mosctl --version
mos version 0.0.10-20-gdd7fbbf
```
Without this, it just says 0.20.

**Comment by raharper** [comment]
What do you think about using go-semver? 

```
package main

import (
	"fmt"

	"github.com/coreos/go-semver/semver"
)

var (
	MachineTypeSecureLatest  *semver.Version
	mTypeInsecureVersion1RAW string = "0.99.99-sketchy"
	mTypeVersion1RAW         string = "1.0.0"
	mTypeVersion1x3RAW       string = "1.3.0"
)

var mTypes = map[string]semver.Version{
	"insecure-version1": {Major: 0, Minor: 99, Patch: 99, PreRelease: "sketchy"},
	"version1":          {Major: 1, Minor: 0, Patch: 0},
	"version1x3":        {Major: 1, Minor: 3, Patch: 0},
}

func GetMachineTypeVersions() semver.Versions {
	versions := semver.Versions{}
	for name, ver := range mTypes {
		fmt.Printf("Name: '%s', Version: '%s'\n", name, ver)
		v := semver.New(ver.String())
		versions = append(versions, v)
	}
	return versions
}

func LatestMachineType(versions semver.Versions) *semver.Version {
	semver.Sort(versions)
	return versions[len(versions)-1]
}

func main() {
	fmt.Printf("Importing Versions...\n")
	versions := GetMachineTypeVersions()
	fmt.Printf("Print semver versions...\n")
	for _, ver := range versions {
		fmt.Printf("- %s\n", ver)
	}
	fmt.Printf("\nGetting 'latest/newest/largest' version from above\n")
	latest := LatestMachineType(versions)
	fmt.Printf("\nlatest: %s\n", latest)
}
```
```
$ ./mt 
Importing Versions...
Name: 'insecure-version1', Version: '0.99.99-sketchy'
Name: 'version1', Version: '1.0.0'
Name: 'version1x3', Version: '1.3.0'
Print semver versions...
- 0.99.99-sketchy
- 1.0.0
- 1.3.0

Getting 'latest/newest/largest' version from above

latest: 1.3.0
```

**Comment by hallyn** [comment]
Getting closer - now it looks like pcr7data fails to get copied into the livecd.  Problem for later.

**Comment by hallyn** [comment]
> What do you think about using go-semver?

Looks like more boilerplate and paperwork, but if it's what the cool kids do...

Sorry I've hadn't noticed this comment, been focusing on the copious failures due to mismatched updates to the other repos...

**Pull request merged**
